name: Test Go

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19"
      - name: tests
        run: find . -name go.mod -execdir go test ./... \;
