name: Test PHP

on:
  push:
    paths:
      - "php/**/*.php"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
          chmod +x phpunit
          mv phpunit /usr/local/bin
      - name: tests
        run: find php -name '*Test.php' -execdir phpunit {} \;
